### PR TITLE
Support rubocop 0.36.0

### PR DESCRIPTION
**Pull request by mainameiz**

### CODE REVIEW

**Comment by jrochkind** [comment]
Does this require rubocop 0.36.0 or will it still work with older ones?

**Comment by mainameiz** [comment]
@jrochkind As I know it requires rubocop 0.36.0 because it has backward incompatible changes.

**Comment by m4i** [comment]
@jrochkind 
I fixed versions earlier than 0.36.0. #12

**Comment by jrochkind** [comment]
@m4i thanks! You're back!  Are you interested in any of the other PR's?  I especially need/want #4, are you interested in that?

**Pull request merged**
